cta:
  train-api-key: ${CTA_TRAIN_API_KEY}
  run: ${CTA_RUN}
mastodon:
  instance: ${MASTODON_INSTANCE}
  access-token: ${MASTODON_ACCESS_TOKEN}
rollbar:
  access-token: ${ROLLBAR_ACCESS_TOKEN}
  environment: ${ROLLBAR_ENVIRONMENT}
