cta:
  train-api-key: ${CTA_TRAIN_API_KEY}
  run: ${CTA_RUN}
twitter:
    access-token: ${TWITTER_ACCESS_TOKEN}
    access-token-secret: ${TWITTER_ACCESS_TOKEN_SECRET}
    api-key: ${TWITTER_API_KEY}
    api-key-secret: ${TWITTER_API_KEY_SECRET}
mastodon:
  instance: ${MASTODON_INSTANCE}
  access-token: ${MASTODON_ACCESS_TOKEN}
bluesky:
  handle: ${BLUESKY_HANDLE}
  app-password: ${BLUESKY_APP_PASSWORD}
rollbar:
  access-token: ${ROLLBAR_ACCESS_TOKEN}
  environment: ${ROLLBAR_ENVIRONMENT}
